# Master configuration file. This holds the definitions and defaults that
# can be set per environment in settings/, or settings.local.yml. Keys can
# certainly be added in secondary files, but be sure to verify that the key
# will be used. Most values are used individually, rather than passing
# along a whole hash or array.

# These are keys used to bridge between settings and the standard Rails files.
rails:
  # Database settings as they will be mapped into database.yml for the running
  # environment. The shell variable DATABASE_URL will always override values
  # in the settings files.
  database:
    adapter: sqlite3
    pool: 5
    timeout: 5000
  # Action Cable settings applied in cable.yml
  cable:
    adapter: async
