# Production environment configuration. These should generally receive values
# in settings.local.yml for deployed instances. If running a multi-environment
# instance for testing or debugging, production.local.yml may be helpful. As-is,
# they are compatible with a typical container-style approach, where default
# ports on generic hostnames are used for each service/resource.

rails:
  database:
    database: db/production.sqlite3
  cable:
    adapter: redis
    url: redis://redis/1
    channel_prefix: cable
